<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INBNRMARITA" failures="1" tests="6" name="Verifier Reject" time="41.569" errors="0" timestamp="2023-05-29T16:26:11 IST">
  <testcase classname="script.VerifierRejectFlow" name="validatePendingReimbursement" time="9.283">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1070] but found [₹1070]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1070] but found [₹1070]
at script.VerifierRejectFlow.validatePendingReimbursement(VerifierRejectFlow.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validatePendingReimbursement -->
  <testcase classname="script.VerifierRejectFlow" name="validateReasonField" time="2.585"/>
  <testcase classname="script.VerifierRejectFlow" name="validateSelectReimTypeField" time="1.023"/>
  <testcase classname="script.VerifierRejectFlow" name="validatePartialPaymentError" time="5.061"/>
  <testcase classname="script.VerifierRejectFlow" name="validateReimSubmitedPopup" time="2.971"/>
  <testcase classname="script.VerifierRejectFlow" name="validateVerifierRemarks" time="5.664"/>
</testsuite> <!-- Verifier Reject -->
