<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INBNRMARITA" failures="1" tests="1" name="SuperAdmin- PO creation" time="48.481" errors="0" timestamp="2022-04-28T13:35:59 IST">
  <testcase classname="script.logintest" name="GenerateIdButton" time="39.833">
    <failure type="java.lang.AssertionError" message="expected [30] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [30] but found [0]
at script.logintest.GenerateIdButton(logintest.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- GenerateIdButton -->
</testsuite> <!-- SuperAdmin- PO creation -->
